client hotspot-network {
    ipaddr = 192.168.0.0/16
    secret = ${SHARED_PASSWORD}
    shortname = hotspot-devices
    nas_type = other
    require_message_authenticator = no
}
client private-network {
    ipaddr = 10.0.0.0/8
    secret = ${SHARED_PASSWORD}
    shortname = private-network
    nas_type = other
}
client docker-network {
    ipaddr = 172.16.0.0/12
    secret = ${SHARED_PASSWORD}
    shortname = docker-network
    nas_type = other
}
client localhost {
    ipaddr = 127.0.0.1
    secret = ${SHARED_PASSWORD}
    shortname = localhost
    nas_type = other
}
