rest {
    tls {
    }
    connect_uri = "http://hotspotapi:8080/radius"
    pool {
        start = 0
        min = 0
        max = 10
        spare = 3
        uses = 0
        lifetime = 0
        idle_timeout = 60
    }
    authorize {
        uri = "${..connect_uri}/authorize"
        method = 'post'
        body = 'json'
        data = '{ "Username": "%{User-Name}", "Password": "%{User-Password}", "NasIpAddress": "%{NAS-IP-Address}", "NasIdentifier": "%{NAS-Identifier}", "CallingStationId": "%{Calling-Station-Id}", "CalledStationId": "%{Called-Station-Id}", "NasPortType": "%{NAS-Port-Type}", "FramedIpAddress": "%{Framed-IP-Address}", "AcctSessionId": "%{Acct-Session-Id}" }'
        tls = ${..tls}
    }
    accounting {
        uri = "${..connect_uri}/accounting"
        method = 'post'
        body = 'json'
        data = '{ "Type": "%{Acct-Status-Type}", "Username": "%{User-Name}", "SessionId": "%{Acct-Session-Id}", "NasIpAddress": "%{NAS-IP-Address}", "NasIdentifier": "%{NAS-Identifier}", "CallingStationId": "%{Calling-Station-Id}", "CalledStationId": "%{Called-Station-Id}", "FramedIpAddress": "%{Framed-IP-Address}", "InputOctets": "%{Acct-Input-Octets}", "OutputOctets": "%{Acct-Output-Octets}", "SessionTime": "%{Acct-Session-Time}", "TerminateCause": "%{Acct-Terminate-Cause}", "EventTimestamp": "%{Event-Timestamp}" }'
        tls = ${..tls}
    }
    post-auth {
        uri = "${..connect_uri}/post-auth"
        method = 'post'
        body = 'json'
        data = '{ "Username": "%{User-Name}", "Status": "%{reply:Packet-Type}", "NasIpAddress": "%{NAS-IP-Address}" }'
        tls = ${..tls}
    }
}
